name: deploy:dev

on:
  push:
    branches:
    - separate-deployments

jobs:
  check-branch:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: branch
      run: echo "branch check is done"

  deploy:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/deploy.yaml
    with:
      domain: dev.${{ vars.ALIAKSEI_YAKUBUK_DOMAIN }}
      domains: ${{ vars.DOMAINS }}
      title: ${{ vars.ALIAKSEI_YAKUBUK_TITLE }}
      description: ${{ vars.ALIAKSEI_YAKUBUK_DESCRIPTION }}
    secrets:
      awsAccessKeyId: ${{ secrets.AWS_CV_ACCESS_KEY }}
      awsSecretAccessKey: ${{ secrets.AWS_CV_SECRET_KEY }}
      awsRegion: ${{ secrets.AWS_CV_REGION }}
