name: deploy:dev

on:
  push:
    branches:
    - master

jobs:

  dev-env:
    uses: ./.github/workflows/deploy.yaml
    with:
      domain: dev.${{ vars.ALIAKSEI_YAKUBUK_DOMAIN }}
      domains: ${{ vars.DOMAINS }}
      title: ${{ vars.ALIAKSEI_YAKUBUK_TITLE }}
      description: ${{ vars.ALIAKSEI_YAKUBUK_DESCRIPTION }}
      type: canonical
      gaTag: test-tag
    secrets:
      awsAccessKeyId: ${{ secrets.AWS_CV_ACCESS_KEY }}
      awsSecretAccessKey: ${{ secrets.AWS_CV_SECRET_KEY }}
      awsRegion: ${{ secrets.AWS_CV_REGION }}
