name: deploy:prod
on:
  push:
    branches:
    - setup-pipeline

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: test
      run: |
        git checkout origin/test-main
        git merge origin/setup-pipeline
        git log -1 --oneline


