name: deploy:prod
on:
  push:
    branches:
    - setup-pipeline

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: test
      run: |
        git -v
        git status
        git log -10 --oneline


