name: deploy:prod
on:
  push:
    branches:
    - setup-pipeline

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: aws-cli-setup
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_CV_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_CV_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_CV_REGION }}

    - name: cleanup
      run: aws s3 rm s3://${{ vars.AWS_CV_PROD_BUCKET_NAME }}/ --recursive

    - name: copy
      run: aws s3 cp s3://${{ vars.AWS_CV_DEV_BUCKET_NAME }}/ s3://${{ vars.AWS_CV_PROD_BUCKET_NAME }}/ --recursive

    - name: invalidation
      run: yarn invalidate


