name: deploy:prod
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: 'Version'
        required: true
        default: minor
        options:
        - patch
        - minor
        - major

jobs:

  aliaksei-yakubuk:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/deploy.yaml
    with:
      domain: ${{ vars.ALIAKSEI_YAKUBUK_DOMAIN }}
      domains: ${{ vars.DOMAINS }}
      title: ${{ vars.ALIAKSEI_YAKUBUK_TITLE }}
      description: ${{ vars.ALIAKSEI_YAKUBUK_DESCRIPTION }}
    secrets:
      awsAccessKeyId: ${{ secrets.AWS_CV_ACCESS_KEY }}
      awsSecretAccessKey: ${{ secrets.AWS_CV_SECRET_KEY }}
      awsRegion: ${{ secrets.AWS_CV_REGION }}

  yakubuk:
    needs: aliaksei-yakubuk
    uses: ./.github/workflows/deploy.yaml
    with:
      domain: ${{ vars.YAKUBUK_DOMAIN }}
      domains: ${{ vars.DOMAINS }}
      title: ${{ vars.ALIAKSEI_YAKUBUK_TITLE }}
      description: ${{ vars.ALIAKSEI_YAKUBUK_DESCRIPTION }}
    secrets:
      awsAccessKeyId: ${{ secrets.AWS_CV_ACCESS_KEY }}
      awsSecretAccessKey: ${{ secrets.AWS_CV_SECRET_KEY }}
      awsRegion: ${{ secrets.AWS_CV_REGION }}

  alexey-yakubuk:
    needs: yakubuk
    uses: ./.github/workflows/deploy.yaml
    with:
      domain: ${{ vars.ALEXEY_YAKUBUK_DOMAIN }}
      domains: ${{ vars.DOMAINS }}
      title: ${{ vars.ALIAKSEI_YAKUBUK_TITLE }}
      description: ${{ vars.ALIAKSEI_YAKUBUK_DESCRIPTION }}
    secrets:
      awsAccessKeyId: ${{ secrets.AWS_CV_ACCESS_KEY }}
      awsSecretAccessKey: ${{ secrets.AWS_CV_SECRET_KEY }}
      awsRegion: ${{ secrets.AWS_CV_REGION }}

  alex-yakubuk:
    needs: alexey-yakubuk
    uses: ./.github/workflows/deploy.yaml
    with:
      domain: ${{ vars.ALEX_YAKUBUK_DOMAIN }}
      domains: ${{ vars.DOMAINS }}
      title: ${{ vars.ALIAKSEI_YAKUBUK_TITLE }}
      description: ${{ vars.ALIAKSEI_YAKUBUK_DESCRIPTION }}
    secrets:
      awsAccessKeyId: ${{ secrets.AWS_CV_ACCESS_KEY }}
      awsSecretAccessKey: ${{ secrets.AWS_CV_SECRET_KEY }}
      awsRegion: ${{ secrets.AWS_CV_REGION }}

  lexa-yakubuk:
    needs: alex-yakubuk
    uses: ./.github/workflows/deploy.yaml
    with:
      domain: ${{ vars.LEXA_YAKUBUK_DOMAIN }}
      domains: ${{ vars.DOMAINS }}
      title: ${{ vars.ALIAKSEI_YAKUBUK_TITLE }}
      description: ${{ vars.ALIAKSEI_YAKUBUK_DESCRIPTION }}
    secrets:
      awsAccessKeyId: ${{ secrets.AWS_CV_ACCESS_KEY }}
      awsSecretAccessKey: ${{ secrets.AWS_CV_SECRET_KEY }}
      awsRegion: ${{ secrets.AWS_CV_REGION }}

  release:
    needs: [aliaksei-yakubuk, yakubuk, alexey-yakubuk, alex-yakubuk, lexa-yakubuk]
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: release
      run: |
        git config user.name ${{ github.actor }}
        git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        yarn version --new-version ${{ inputs.version }}
        git push https://${{ github.actor }}:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git ${{ github.ref }} --follow-tags

  invalidation:
    needs: release
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: aws-cli-setup
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_CV_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_CV_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_CV_REGION }}

    - name: invalidation
      run: yarn invalidate
